= Cheminformatics Toolkit SMILES Documentation Support Comparison
:toc: macro

v0.1, 2019-07-25                                +
https://iupac.org/projects/project-details/?project_nr=2019-002-2-024[IUPAC SMILES+ Project No. 2019-002-024]    +
Copyright © 2019, IUPAC

This document provides information about SMILES compatibility between toolkits
based on their documentation focusing on SMILES, aromaticity models, and SMILES extensions.
Of course, in practice, individual compatibility of toolkits cannot be assessed by
documentation alone (e.g., two differently named/described aromaticity models may have identical behavior
depending on the input SMILES). As such, consider this document only as a broad survey of compatibility
and SMILES features.

*Two important notes:*

1. We have endeavored to provide accurate information about cheminformatics toolkit SMILES support,
aromaticity models, and extensions. If we have inferred something incorrectly from the available
documentation, please let us know and we will fix it immediately.

2. A comparison of SMILES reaction extensions and transform queries (e.g., SMIRKS) is outside the scope of this
document.

*Selected Summary Tables*

.OpenSMILES Support Mentioned in Docs
[cols="2,1"]
[width="50%"]
|===
|Toolkit |OpenSMILES

|CACTVS v3.4.8.3 | -
|*CDK v2.0* | *✓*
|ChemAxon 2019 | -
|*ChemDoodle v9.1* | *✓*
|Indigo 1.3.0 beta | -
|*Jmol 14.29* | *✓*
|KnowItAll 2018 | -
|OEChem 2.2.0 | -
|*Open Babel v3.0.0rc1* | *✓*
|RDKit v2019.03.1| -

|===

.SMILES Higher Order Stereochemistry Support (e.g., allenal (AL), square planar (SP), trigonal Bipyramidal (TB), and octahedral (OH))
[cols="2,3"]
[width="50%"]
|===
|Toolkit | SMILES Higher Order Stereochemistry Support

|*CACTVS v3.4.8.3* | *AL, SP, TB, OH*
|*CDK v2.0* | *AL, SP, TB, OH*
|ChemAxon 2019 | -
|ChemDoodle v9.1 | ?
|*Indigo 1.3.0 beta* | *AL*
|*Jmol 14.29* | *AL, SP, TB, OH*
|*KnowItAll 2018* | *AL*
|OEChem 2.2.0 | -
|*Open Babel v3.0.0rc1* | *AL, SP, TB, OH*
|RDKit v2019.03.1| -

|===

Note that CACTVS has partial support for TB and OH, see notes below.

.Specific Aromaticity Models Supported as Mentioned by Name
[cols="2,1,1,1,1,1,1"]
[width="70%"]
|===
|Toolkit | Internal Model(s) |  Daylight (like) | Tripos | MDL | MMFF | Customizable

|CACTVS v3.4.8.3 | ✓ | ✓ | ✓ | - | - | ✓
|CDK v2.0 | ✓ | ✓ | - |  ✓ | - | ✓
|ChemAxon 2019 | ✓  | ✓  | -  | -  | - | -
|ChemDoodle v9.1 | ✓ | - | - | - | - | -
|Indigo 1.3.0 beta | ✓ | - | - | - | - | -
|Jmol 14.29 | ✓ | - | - | - | - | ✓
|KnowItAll 2018 | ✓ | - | - | - | - | -
|OEChem 2.2.0 | ✓ | ✓ | ✓ | ✓ | ✓ | -
|Open Babel v3.0.0rc1 | ✓ | ✓ | - | - | - | ✓
|RDKit v2019.03.1| ✓ | - | - | ✓ | - | ✓

|===

.SMILES Extensions Supported as noted in documentation (selected overview, included extensions that two or more toolkits support*)
[cols="2,1,1,3,1,1,1"]
[width="70%"]
|===
|Toolkit | Daylight SMARTS** | CXSMILES | R Groups `[Z]` or `[R]` | Aromatic `[te]` | Quadruple Bonds `$` | Ring Closures > 100 (`%(nnn)`)

|CACTVS v3.4.8.3 | ✓ | - | ✓ | ✓ | - | -
|CDK v2.0 | ✓ | ✓ | ✓ | ✓ | - | -
|ChemAxon 2019 |  ✓ | ✓ | ✓ | - | - | -
|ChemDoodle v9.1 | ✓ | - | - | - | - | -
|Indigo 1.3.0 beta | ✓ | ✓ | - | - | - | -
|Jmol 14.29 | ✓ | - | - | - | ✓ | ✓
|KnowItAll 2018 | - | - | ✓ | ✓ | ✓ | -
|OEChem 2.2.0 | ✓ | - | ✓ | ✓ | ✓ | -
|Open Babel v3.0.0rc1 | ✓ | - | - | - | - | ✓
|RDKit v2019.03.1| ✓ | ✓ | - | ✓ | - | ✓

|===

*see below notes for other extensions that individual toolkits support such as RDKit's extensions for
dative bonds (`- >` and `< -`). Moreover, some of the toolkit extension support may require specific settings
or only allow reading, not writing of the extension (see below).

**some toolkits note features of Daylight SMARTS that they do not support and additional extensions to SMARTS that they do
support (see below notes and resource links).

toc::[]
:toclevels: 5
:sectnums:

== Avalon

https://sourceforge.net/p/avalontoolkit/wiki/Home/[Avalon Cheminformatics Toolkit]

We could not find any public documentation describing the Avalon Cheminformatics Toolkit SMILES
parsing/compatibility behavior.

== BIOVIA Draw

https://www.3dsbiovia.com/products/collaborative-science/biovia-draw/[BIOVIA Draw]

We could not find any public documentation describing the BIOVIA Draw Toolkit SMILES
parsing/compatibility behavior.

== CACTVS

=== SMILES

https://www.xemistry.de/docs/html/tcl_reference-49.htm#635324256_pgfId-624130[CACTVS Toolkit: SMILES and SMARTS Dialects]

The CACTVS v3.4.8.3 toolkit implements and supports Daylight SMILES. Higher order stereochemistry
including octahedral and trigonal bi-pyramidal structures can be read and written if present, but not generated
or perceived from other descriptors. There is full support for allenal and square planar stereochemistry.

=== Aromaticity

https://www.xemistry.de/docs/cactvs_full.pdf[CACTVS Tcl Scripting Introduction]

The CACTVS v3.4.8.3 aromaticity model is described as more selective than the Daylight toolkit interpretation.
(e.g., rings with exocyclic keto groups are aromatic with Daylight, but not CACTVS). CACTVS also supports
the Daylight, Tripos, and custom user aromaticity models.

=== Extensions

https://www.xemistry.de/docs/html/tcl_reference-49.htm#635324256_pgfId-624130[CACTVS Toolkit: SMILES and SMARTS Dialects]

==== Aromatic Extension

CACTVS v3.4.8.3 supports aromatic tellerium (`[te]`).

==== R Groups

R groups (e.g., `R` and `Z`) as well as Beilstein query atoms such as `[ALK]` are supported in CACTVS.

==== SMARTS

The CACTVS v3.4.8.3 toolkit supports Daylight SMARTS with the exception of higher order stereochemistry (e.g., octahedral
and bi-pyramidal substructure matching). The default CACTVS
SMARTS matching is less selective than Daylight, however there is an option for
strict interpretation to more closely align with the Daylight SMARTS matching.

Numerous SMARTS extensions are supported such as attribute ranges (e.g., `[X{2-3}]`), `D` for deuterium, match counts,
additional atom attributes (e.g., `X` without number for heteroatom matching), and most Eli Lilly
extended SMARTS (e.g., `/IWfss` for matching number of SSSR rings).

There is also an option to specify the Daylight SMILES release number to use for encoding/decoding
SMARTS (e.g., Daylight v. 4.9).

== CDK v2.0

=== SMILES

https://jcheminf.biomedcentral.com/track/pdf/10.1186/s13321-017-0220-4[Willighagen et al. J Cheminform (2017) 9:33; DOI 10.1186/s13321-017-0220-4]

http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/smiles/SmilesGenerator.html[CDK Class SmilesGenerator]

The CDK v2.0 toolkit supports Daylight SMILES and OpenSMILES.
Unsupported features in the http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/smiles/SmilesParser.html[SmilesParser]
include variable order of bracket atom attributes and atom class indication. Higher order
http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/stereo/package-summary.html[stereochemistry] is fully supported.

=== Aromaticity

http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/aromaticity/Aromaticity.html[CDK Class Aromaticity]

There are several aromaticity models supported in CDK 2.0 that allow users to configure the model with a specific
http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/aromaticity/ElectronDonation.html[electron donation model]
(CDK model, CDK model allowing exocyclic contributions, pi bond model (MDL-like), variant close to Daylight)
and http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/graph/CycleFinder.html[cycle finder] method.

=== Extensions

==== Aromatic Extension

Aromatic tellerium is supported (`[te]`) in CDK for reading, but not writing (see https://github.com/vfscalfani/IUPAC_SMILES_plus/pull/1[pull request #1]).

==== R Groups

CDK supports [R1] on read, but not write. R Groups can, however, be written as CXSMILES wtih CDK.
(see https://github.com/vfscalfani/IUPAC_SMILES_plus/pull/1[pull request #1]).

==== CXSMILES

http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/smiles/SmiFlavor.html[CDK Class SmiFlavor]

CDK v2.0 supports ChemAxon Extended SMILES

==== SMARTS

http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/smarts/Smarts.html[CDK Class Smarts]

Daylight SMARTS are supported as well as other selected extensions from CACTVS, MOE, and OEChem.

== ChemAxon

=== SMILES

https://docs.chemaxon.com/display/docs/SMILES[ChemAxon Documentation SMILES]

ChemAxon supports Daylight SMILES. ChemAxon implements a custom specification of SMILES, which has a few noted differences
compared to Daylight (from what we can infer) such as the `[Z]` symbol supported for R-group attachments,
and addition of radicals stored in CXSMILES (see below) upon import for certain atoms when
implicit hydrogens can not be added. Higher level stereochemistry is not supported in SMILES parsing including
allene like, square planar, trigonal-bipyramidal, and octahedral.

=== Aromaticity

https://docs.chemaxon.com/display/docs/Methods[ChemAxon Documentation Methods]

ChemAxon Marvin supports four aromaticity models including a basic aromaticity model, general aromaticity detection
(incorporates mesomeric and tautomeric rearrangement, similar to Daylight), loose aromaticity detection,
and ambiguous aromaticity detection.

=== Extensions

==== SMARTS

https://docs.chemaxon.com/display/docs/SMARTS[ChemAxon Documentation SMARTS]
Daylight SMARTS are supported with some noted limitations to edit SMARTS in the Marvin GUI interface,
however evaluation of the query works.

==== CXSMILES and CXSMARTS

https://docs.chemaxon.com/display/docs/ChemAxon+Extended+SMILES+and+SMARTS+-+CXSMILES+and+CXSMARTS[ChemAxon Extended SMILES and SMARTS]

ChemAxon has developed many feature extensions for SMILES and SMARTS that store information after the SMILES string. Some of the
features include denoting information about atom properties, pseudo atoms, R-groups, enhanced stereochemistry, polymer groups, and more.

== ChemDoodle

=== SMILES

https://www.chemdoodle.com/downloads/ChemDoodleUserGuide.pdf[ChemDoodle v9.1 User Guide]

ChemDoodle v9.1 supports Daylight and also follows recommendations in OpenSMILES. ChemDoodle supports custom
atom/group abbreviations and allows the abbreviation to be expanded as SMILES.

=== Aromaticity

https://www.chemdoodle.com/downloads/ChemDoodleUserGuide.pdf[ChemDoodle v9.1 User Guide]

ChemDoodle v9.1 supports one aromaticity model. The aromaticity model is based on the Hueckel method, where rings are assumed planar, and
hybridized heteroatoms contribute.

=== Extensions

https://www.chemdoodle.com/downloads/ChemDoodleUserGuide.pdf[ChemDoodle v9.1 User Guide]

==== SMARTS

ChemDoodle v9.1 supports Daylight SMARTS. No limitations to syntax support is mentioned.

== ChemDraw

https://www.perkinelmer.com/category/chemdraw[Perkin Elmer ChemDraw]

We could not find any public documentation describing the Perkin Elmer ChemDraw Toolkit SMILES parsing/compatibility behavior.

== Indigo

=== SMILES

https://lifescience.opensource.epam.com/indigo/concepts/index.html[Indigo Toolkit Concepts: File Formats]

Indigo 1.3.0 beta supports Daylight SMILES. Allenal stereochemistry is supported. Noted unsupported features include unspecified up or down notation (`/?` or `\?`)
and higher level stereochemistry including square-planar, trigonal bipyramidal, and octahedral.

=== Aromaticity

https://lifescience.opensource.epam.com/indigo/options/aromaticity.html#aromaticity-model[Indigo Toolkit Options: Aromaticity Options]

Indigo 1.3.0 beta supports two aromaticity models. A basic model where external double bonds for aromatic rings are not allowed,
and a generic model where external double bonds are allowed.

=== Extensions

https://lifescience.opensource.epam.com/indigo/concepts/index.html[Indigo Toolkit Concepts: File Formats]

==== CXSMILES

ChemAxon Extended SMILES are supported in Indigo including radical numbers, stereogroups, pseudo atoms, and fragment grouping in reactions.

==== CurlySMILES

Indigo supports the CurlySMILES extensions for simple polymers and multiple groups.

==== SMARTS

Daylight SMARTS are supported in Indigo. The only noted unsupported features are implicit hydrogen count and any features
not supported in the SMILES parsing (see above).

== Jmol

=== SMILES

https://chemapps.stolaf.edu/jmol/docs/#jmolsmarts/smiles[Jmol/JSmol interactive scripting documentation: Jmol SMARTS/SMILES]

https://jcheminf.biomedcentral.com/track/pdf/10.1186/s13321-016-0160-4[Hanson J. Cheminform. (2016) 8:50; DOI: 10.1186/s13321-016-0160-4]

Jmol 14.29 supports OpenSMILES. There is full support for higher order stereochemistry including
allenal, square planar, trigonal Bipyramidal, and octahedral. The Jmol SMILES extensions support
additional stereochemistry notations (see below).

=== Aromaticity

https://jcheminf.biomedcentral.com/track/pdf/10.1186/s13321-016-0160-4[Hanson J. Cheminform. (2016) 8:50; DOI: 10.1186/s13321-016-0160-4]

Jmol supports two aromaticity models including an open (OpenSMILES definition, Hueckel's rule
allowing exocyclic double bonds) and strict option (3D planarity, no exocyclic double bonds).
There is also an option to have no aromaticity checks.

=== Extensions

==== Jmol SMILES

https://jcheminf.biomedcentral.com/track/pdf/10.1186/s13321-016-0160-4[Hanson J. Cheminform. (2016) 8:50; DOI: 10.1186/s13321-016-0160-4]

Jmol SMILES is a superset of OpenSMILES and includes a variety of extensions such as
dummy atoms (`[Xx]`), unlimited connectivity numbers (`%(nnn)`), and advanced notation for
T-shape, see-saw, and atropisomer stereochemistry. Note also that Jmol supports quadruple bonds,
`$` (as defined in OpenSMILES specification).

==== SMARTS

Jmol supports https://github.com/timvdm/OpenSMARTS[OpenSMARTS] and
https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html[Daylight SMARTS]
with a few noted exceptions such as no support for unspecified designations (`/?`,`\?`, and `@...?`),
interpretation of `>>` as `.`, and differing behavior related to ring-membership primitives
(`r<n>` and `R<n>``).

==== Jmol SMARTS

Jmol significantly extends and modifies OpenSMARTS with a variety of additions to the syntax such as
querying for atom index (`=<n>`), a variable number of pattern occurrences (`$min-max(pattern)`), and
angles within an x-y range (`A(.a:x-y)BC`).

== KnowItAll

http://www.bio-rad.com/en-us/product/knowitall-academic-edition-free-chemistry-software?ID=NH29WJ15[KnowItAll 2018]

Note: documentation about KnowItAll 2018 SMILES parsing and support is not available, however
Bio-Rad kindly provided the following information.

=== SMILES

KnowItAll 2018 supports Daylight SMILES. Allenal stereochemistry is fully supported. There is not
currently support for square planar, trigonal bipyramidal, and octahedral stereochemistry.

=== Aromaticity

KnowItAll 2018 has an internal aromaticity model, however no aromaticity model is applied to
SMILES parsing and writing. 

=== Extensions

==== R Groups

KnowItAll 2018 supports SMILES R groups (`[Z]` and `[R]`).

==== Aromatic Extension

Aromatic `[te]` is supported in KnowItAll 2018.

==== Quadruple Bonds

Quadruple bonds are supported in KnowItAll with the `$` symbol.

==== Ring Closures > 100

Ring closures, `%(NNN)`, will be supported in the next version of KnowItAll.

== OEChem

=== SMILES

https://docs.eyesopen.com/toolkits/python/oechemtk/SMILES.html#chapter-smiles[OEChem Toolkit 2.2.0: SMILES Line Notation]

OEChem 2.2.0 support Daylight SMILES with a variety of noted differences and ambiguities where certain SMILES
are either read or rejected. There is a strict mode or default relaxed mode to adjust the behavior of the SMILES parser.
According to the https://docs.eyesopen.com/toolkits/python/oechemtk/stereochemistry.html[stereochemistry perception docs],
only tetrahedral and cis/trans configurations are supported.

=== Aromaticity

https://docs.eyesopen.com/toolkits/python/oechemtk/aromaticity.html[OEChem Toolkit 2.2.0: Aromaticity Perception]

OEChem 2.2.0 supports five different aromaticity models including a default OpenEye model, Daylight, Tripos, MDL, and MMFF.

=== Extensions

https://docs.eyesopen.com/toolkits/python/oechemtk/SMILES.html#chapter-smiles[OEChem Toolkit 2.2.0: SMILES Line Notation]

==== Quadruple Bonds

Quadruple bonds are supported in OEChem with the `$` symbol.

==== Additional Atom Elements

OEChem 2.2.0 supports additional unquoted (e.g., `D` for deuterium) and additional elements (e.g., `[Sg]`).

==== Aromatic Extension

Aromatic tellerium is supported (`[te]`)

==== Atom Maps

OEChem 2.2.0 allows atom maps in not only reaction SMILES, but also discrete molecules (e.g., `[Pb:1]`)

==== R Groups and External Bond Attachments

OEChem 2.2.0 has compatibility with R group notation (`[R2]`). The toolkit also supports unpaired external
attachment points (e.g., `CC&1`) to allow for string concatenation of individual components.

==== SMARTS

https://docs.eyesopen.com/toolkits/python/oechemtk/SMARTS.html[OEChem Toolkit 2.2.0: SMARTS Pattern Matching]

OEChem 2.2.0 supports Daylight SMARTS with the a noted difference of the behavior of the ring count primitive, `R`. Atomic
hybridization queries are also supported with the symbol `^`.

== Open Babel

=== SMILES

http://openbabel.org/docs/current/FileFormats/SMILES_format.html[Open Babel v2.3.1 SMILES Format]

Open Babel implements the OpenSMILES specification. There is also a specific parser, https://open-babel.readthedocs.io/en/latest/FileFormats/SMILES_format_using_Smiley_parser.html[Smiley parser],
which includes strict support for the OpenSMILES specification, including higher order stereochemistry (from what we can infer).

=== Aromaticity

https://open-babel.readthedocs.io/en/latest/Aromaticity/Aromaticity.html[Open Babel v3.0.0rc1 Handling of Aromaticity]

One aromaticity model is supported in Open Babel, which is described as similar to
the Daylight aromaticity model. This model was discussed at the 254th ACS Meeting:
https://www.slideshare.net/baoilleach/we-need-to-talk-about-kekulization-aromaticity-and-smiles[We need to talk about...Kekulization, Aromaticity, and SMILES by N.M. O'Boyle and J.W. Mayfield]

It is possible for users to apply custom aromaticity models in Open Babel and aromaticity in the original SMILES input can be maintained with the `-aa` read option.

=== Extensions

==== Radicals and Conjugated Chains

http://openbabel.org/docs/current/Features/Radicals.html[Open Babel v2.3.1 Radicals and SMILES extensions]

Open Babel supports two SMILES radical extensions: (1) radicals can be interpreted
without defining hydrogens explicitly (e.g., `C[O.]` or `C[O]` for a methoxy radical CH~3~O),
and (2) radical centers can be interpreted with lowercase atomic symbols (e.g., ethyl radical is `Cc`)

There is also support for conjugated carbon chains by interpreting multiple
sequential lower case c without a ring closure (e.g., `cccc` as conjugated carbon chains.

==== Ring Closures > 100

https://github.com/openbabel/openbabel/pull/1677[Open Babel Pull Request #1677]

Open Babel supports ring closures up to 5 digits `%(NNNNN)`

==== SMARTS

https://openbabel.org/wiki/SMARTS[Open Babel SMARTS]

Open Babel supports Daylight SMARTS with an additional extension to match atom
hybridization with a `^` symbol (e.g., sp^3^ carbon hybridization, `[#6^3]`).

There are several known limitations to the SMARTS support in Open Babel such as
no support for cis/trans stereochemistry and component level grouping.

== RDKit

=== SMILES

https://www.rdkit.org/docs/RDKit_Book.html#smiles-support-and-extensions[RDKit Book SMILES Support and Extensions]

RDKit 2019.03.1 supports Daylight SMILES. Higher order stereochemistry is not supported.

=== Aromaticity

https://www.rdkit.org/docs/RDKit_Book.html#aromaticity[RDKit Book Aromaticity]

RDKit 2019.03.1 supports three aromaticity models: (1) the RDKit aromaticity model, which is based on Hueckel's rule and defined
atom and environment electron contributions; (2) a simple aromaticity model, where only 5 and 6 membered rings are
considered for aromaticity; and (3) the MDL aromaticity model. There is also an option for users to define their own aromaticity models.

=== Extensions

https://www.rdkit.org/docs/RDKit_Book.html#smiles-support-and-extensions[RDKit Book SMILES Support and Extensions]

==== Aromatic Extension

RDKit supports aromatic tellerium (`[te]`)

==== Dative Bonds

The symbols `- >` and `< -` can be used in RDKit to specify dative bonds.

==== Atomic Number

Carbon can be specified with SMARTS notation `[#6]` in RDKit SMILES.

==== Ring Closures > 100

https://github.com/rdkit/rdkit/pull/1624[RDKit Pull Request #1624]
RDKit supports ring closures up to 5 digits `%(NNNNN)`

==== CXSMILES

RDKit supports a variety of ChemAxon Extended SMILES including reading and writing of atomic coordinates,
atomic values, atomic labels, atomic properties, radicals, and enhanced stereo. The coordinate bond extension
can be read, but not written in RDKit.

==== SMARTS

RDKit supports Daylight SMARTS with the following unsupported features: non-tetrahedral chiral classes,
the `@?` operator, explicit atomic masses, and component level grouping.

There are several extensions to SMARTS that are supported in RDKit including hybridization queries with
the symbol (e.g., `^2`, for SP^2^), dative bonds (e.g., `- >`), heteroatom neighbor queries with the symbol `z`,
and range queries.
