= Cheminformatics Toolkit SMILES Documentation Support Comparison
:toc: macro

This document provides information about SMILES compatibility between toolkits
based on their documentation focusing on SMILES, aromaticity models, and SMILES extensions. Of course, in practice,
individual compatibility of toolkits cannot be assessed by documentation alone (e.g., two different
aromaticity models may have identical behavior depending on the input SMILES. Despite these limitations, we have found this
a useful exercise to "survey" current toolkit SMILES documentation and compile our findings and links to toolkit documentation pages for reference.

*Two important notes:*

1. We have endeavored to provide accurate information about cheminformatics toolkit SMILES support, aromaticity models, and extensions.
If we have inferred something incorrectly from the available documentation, please let us know and we will fix it immediately.

2. A comparison of SMILES reaction extensions and transform queries (e.g., SMIRKS) is outside the scope of this
document.

*Summary Tables*

SMILES Daylight and Open SMILES
Aromaticity
Extensions

v0.1, 2019-07-25                                +
https://iupac.org/projects/project-details/?project_nr=2019-002-2-024[IUPAC SMILES+ Project No. 2019-002-024]    +

toc::[]
:toclevels: 5
:sectnums:

== Avalon

https://sourceforge.net/p/avalontoolkit/wiki/Home/[Avalon Cheminformatics Toolkit]

We could not find any public documentation describing the Avalon Cheminformatics Toolkit SMILES parsing/compatibility behavior.

== BIOVIA Draw

https://www.3dsbiovia.com/products/collaborative-science/biovia-draw/[BIOVIA Draw]

We could not find any public documentation describing the BIOVIA Draw Toolkit SMILES parsing/compatibility behavior.

== CACTVS

=== SMILES

https://www.xemistry.de/docs/html/tcl_reference-49.htm#635324256_pgfId-624130[CACTVS Toolkit: SMILES and SMARTS Dialects]

The CACTVS toolkit implements and supports Daylight SMILES, including reaction SMILES. Higher order stereochemistry
including octahedral and bi-pyramidal structures can be read and written.

=== Aromaticity

https://www.xemistry.de/docs/cactvs_full.pdf[CACTVS Tcl Scripting Introduction]

The CACTVS aromaticity model is described as more selective than the Daylight toolkit interpretation.
(e.g., rings with exocyclic keto groups are aromatic with Daylight, but not CACTVS). However, there is
a daylight aromaticity model available as an option for substructure matching.

=== Extensions

==== SMARTS

https://www.xemistry.de/docs/html/tcl_reference-49.htm#635324256_pgfId-624130[CACTVS Toolkit: SMILES and SMARTS Dialects]

The CACTVS toolkit supports Daylight SMARTS with the exception of higher order stereochemistry (e.g., octahedral
and bi-pyramidal substructure matching). The default CACTVS
SMARTS matching is less selective than Daylight, however there is an option for
strict interpretation to more closely align with the Daylight SMARTS matching.

Numerous SMARTS extensions are supported such as attribute ranges (e.g., `[X{2-3}]`), match counts,
additional atom attributes (e.g., `X` without number for heteroatom matching), and most Eli Lilly
extended SMARTS (e.g., `/IWfss` for matching number of SSSR rings).

There is also an option to specify the Daylight SMILES release number to use for encoding/decoding
SMARTS (e.g., Daylight v. 4.9)

== CDK v2.0

=== SMILES

https://jcheminf.biomedcentral.com/track/pdf/10.1186/s13321-017-0220-4[Willighagen et al. J Cheminform (2017) 9:33; DOI 10.1186/s13321-017-0220-4]

http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/smiles/SmilesGenerator.html[CDK Class SmilesGenerator]

The CDK v2.0 toolkit supports Daylight SMILES, OpenSMILES, and reaction SMILES.
Unsupported features in the http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/smiles/SmilesParser.html[SmilesParser]
include higher order stereochemistry (square planar, trigonal Bipyramidal, and octahedral), in addition to
variable order of bracket atom attributes and atom class indication.

=== Aromaticity

http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/aromaticity/Aromaticity.html[CDK Class Aromaticity]

There are several aromaticity models supported in CDK 2.0 that allow users to configure the model with a specific
http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/aromaticity/ElectronDonation.html[electron donation model]
(CDK model, CDK model allowing exocyclic contributions, pi bond model, and a variant close to Daylight)
and http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/graph/CycleFinder.html[cycle finder] method.

=== Extensions

==== CXSMILES

http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/smiles/SmiFlavor.html[CDK Class SmiFlavor]

CDK v2.0 supports ChemAxon Extended SMILES

==== SMARTS

http://cdk.github.io/cdk/2.2/docs/api/org/openscience/cdk/smarts/Smarts.html[CDK Class Smarts]

Daylight SMARTS are supported as well as other extensions from CACTVS, MOE, and OEChem.

== ChemAxon

=== SMILES

https://docs.chemaxon.com/display/docs/SMILES[ChemAxon Documentation SMILES]

ChemAxon Marvin implements a custom specification of SMILES, which has a few noted differences compared to Daylight (from what we can infer) such as
the `[Z]` symbol supported for R-group attachments, and addition of radicals stored in CXSMILES (see below) upon import for certain atoms when
implicit hydrogens can not be added. Reaction SMILES are supported. Higher level stereochemistry is not supported in SMILES parsing including
allene like, square planar, trigonal-bipyramidal, and octahedral. In addition, branching is not supported in cases where there is no atom preceding the branch.

=== Aromaticity

https://docs.chemaxon.com/display/docs/Methods[ChemAxon Documentation Methods]

ChemAxon Marvin supports four aromaticity models including a basic aromaticity model, general aromaticity detection (incorporates mesomeric and tautomeric rearrangement,
similar to Daylight), loose aromaticity detection, and ambiguous aromaticity detection.

=== Extensions

==== SMARTS

https://docs.chemaxon.com/display/docs/SMARTS[ChemAxon Documentation SMARTS]
Daylight SMARTS are supported with some noted limitations to edit SMARTS in the Marvin GUI interface, however evaluation of the query works.

==== CXSMILES and CXSMARTS

https://docs.chemaxon.com/display/docs/ChemAxon+Extended+SMILES+and+SMARTS+-+CXSMILES+and+CXSMARTS[ChemAxon Extended SMILES and SMARTS]

ChemAxon has developed many feature extensions for SMILES and SMARTS that store information after the SMILES string. Some of the
features include denoting information about atom properties, pseudo atoms, R-groups, enhanced stereochemistry, polymer groups, and more.


== ChemDoodle

=== SMILES

https://www.chemdoodle.com/downloads/ChemDoodleUserGuide.pdf[ChemDoodle v9.1 User Guide]

ChemDoodle v9.1 supports Daylight and also follows recommendations in OpenSMILES. ChemDoodle supports custom
atom/group abbreviations and allows the abbreviation to be expanded as SMILES.

=== Aromaticity

https://www.chemdoodle.com/downloads/ChemDoodleUserGuide.pdf[ChemDoodle v9.1 User Guide]

ChemDoodle v9.1 supports one aromaticity model. The aromaticity model is based on the Hueckel method, where rings are assumed planar, and
hybridized heteroatoms contribute.

=== Extensions

==== SMARTS

https://www.chemdoodle.com/downloads/ChemDoodleUserGuide.pdf[ChemDoodle v9.1 User Guide]

ChemDoodle v9.1 supports Daylight SMARTS. No limitations to syntax support is mentioned.

== ChemDraw

https://www.perkinelmer.com/category/chemdraw[Perkin Elmer ChemDraw]

We could not find any public documentation describing the Perkin Elmer ChemDraw Toolkit SMILES parsing/compatibility behavior.

== KnowItAll

== Indigo

=== SMILES

https://lifescience.opensource.epam.com/indigo/concepts/index.html[Indigo Toolkit Concepts: File Formats]

Indigo 1.3.0 beta supports Daylight SMILES. Noted unsupported features include unspecified up or down notation (`/?` or `\?`)
and higher level stereochemistry including square-planar, trigonal bipyramidal, and octahedral.

=== Aromaticity

https://lifescience.opensource.epam.com/indigo/options/aromaticity.html#aromaticity-model[Indigo Toolkit Options: Aromaticity Options]
Indigo 1.3.0 beta supports two aromaticity models. A basic model where external double bonds for aromatic rings are not allowed,
and a generic model where external double bonds are allowed.

=== Extensions

==== CXSMILES

https://lifescience.opensource.epam.com/indigo/concepts/index.html[Indigo Toolkit Concepts: File Formats]
ChemAxon Extended SMILES are supported in Indigo including radical numbers, stereogroups, pseudo atoms, and fragment grouping in reactions.

==== CurlySMILES

https://lifescience.opensource.epam.com/indigo/concepts/index.html[Indigo Toolkit Concepts: File Formats]
Indigo supports the CurlySMILES extensions for simple polymers and multiple groups.

==== SMARTS

https://lifescience.opensource.epam.com/indigo/concepts/index.html[Indigo Toolkit Concepts: File Formats]
Daylight SMARTS are supported in Indigo. The only noted unsupported features are implicit hydrogen count and any features
not supported in the SMILES parsing (see above).

== OEChem

== Open Babel

=== SMILES

http://openbabel.org/docs/current/FileFormats/SMILES_format.html[Open Babel v2.3.1 SMILES Format]

Open Babel implements the OpenSMILES specification. Open Babel also supports reading and writing of reaction SMILES (.rsmi):
http://openbabel.org/docs/current/FileFormats/Reaction_Formats.html[Open Babel Reaction Formats]

=== Aromaticity

https://open-babel.readthedocs.io/en/latest/Aromaticity/Aromaticity.html[Open Babel v3.0.0rc1 Handling of Aromaticity]

One aromaticity model is supported in Open Babel, which is described as similar to
the Daylight aromaticity model. This model was discussed at the 254th ACS Meeting:
https://www.slideshare.net/baoilleach/we-need-to-talk-about-kekulization-aromaticity-and-smiles[We need to talk about...Kekulization, Aromaticity, and SMILES by N.M. O'Boyle and J.W. Mayfield]

Aromaticity in the original SMILES input can also be maintained with the `-aa` read option.

=== Extensions

==== Radicals and Conjugated Chains

http://openbabel.org/docs/current/Features/Radicals.html[Open Babel v2.3.1 Radicals and SMILES extensions]

Open Babel supports two SMILES radical extensions: (1) radicals can be interpreted
without defining hydrogens explicitly (e.g., `C[O.]` or `C[O]` for a methoxy radical CH~3~O),
and (2) radical centers can be interpreted with lowercase atomic symbols (e.g., ethyl radical is `Cc`)

There is also support for conjugated carbon chains by interpreting multiple
sequential lower case c without out a ring closure (e.g., `cccc` as conjugated carbon chains.

==== SMARTS

https://openbabel.org/wiki/SMARTS[Open Babel SMARTS]

Open Babel supports Daylight SMARTS with an additional extension to match atom
hybridization with a `^` symbol (e.g., sp^3^ carbon hybridization, `[#6^3]`).

There are several known limitations to the SMARTS support in Open Babel such as
no support for cis/trans stereochemistry and component level grouping.

== RDKit
