= Cheminformatics Toolkit SMILES Documentation Support Comparison
:toc: macro

This document provides information about SMILES compatibility between toolkits
based on their documentation focusing on SMILES, aromaticity models, and SMILES extensions.
A comparison of SMILES reaction extensions and transform queries (e.g., SMIRKS) is outside the scope of this
document.

v0.1, 2019-06-09                                +
https://iupac.org/projects/project-details/?project_nr=2019-002-2-024[IUPAC SMILES+ Project No. 2019-002-024]    +

toc::[]
:toclevels: 5
:sectnums:

== Avalon

https://sourceforge.net/p/avalontoolkit/wiki/Home/[Avalon Cheminformatics Toolkit]

We could not find any public documentation describing the Avalon Cheminformatics Toolkit SMILES parsing/compatibility behavior.

== BIOVIA Draw

https://www.3dsbiovia.com/products/collaborative-science/biovia-draw/[BIOVIA Draw]

We could not find any public documentation describing the BIOVIA Draw Toolkit SMILES parsing/compatibility behavior.

== CACTVS

=== SMILES

https://www.xemistry.de/docs/html/tcl_reference-49.htm#635324256_pgfId-624130[CACTVS Toolkit: SMILES and SMARTS Dialects]

The CACTVS toolkit implements and supports Daylight SMILES, including reaction SMILES.

=== Aromaticity

https://www.xemistry.de/docs/cactvs_full.pdf[CACTVS Tcl Scripting Introduction]

The CACTVS aromaticity model is described as more selective than the Daylight toolkit interpretation.
(e.g., rings with exocyclic keto groups are aromatic with Daylight, but not CACTVS). However, there is
a daylight aromaticity model available as an option for substructure matching.


== CDK

== ChemAxon

== ChemDoodle

== ChemDraw

== KnowItAll

== Indigo

== OEChem

== Open Babel

=== SMILES

http://openbabel.org/docs/current/FileFormats/SMILES_format.html[Open Babel v2.3.1 SMILES Format]

Open Babel implements the OpenSMILES specification. Open Babel also supports reading and writing of reaction SMILES (.rsmi):
http://openbabel.org/docs/current/FileFormats/Reaction_Formats.html[Open Babel Reaction Formats]

=== Aromaticity

https://open-babel.readthedocs.io/en/latest/Aromaticity/Aromaticity.html[Open Babel v3.0.0rc1 Handling of Aromaticity]

One aromaticity model is supported in Open Babel, which is described as similar to
the Daylight aromaticity model. This model was discussed at the 254th ACS Meeting:
https://www.slideshare.net/baoilleach/we-need-to-talk-about-kekulization-aromaticity-and-smiles[We need to talk about...Kekulization, Aromaticity, and SMILES by N.M. O'Boyle and J.W. Mayfield]

Aromaticity in the original SMILES input can also be maintained with the `-aa` read option.

=== Extensions

==== Radicals and Conjugated Chains

http://openbabel.org/docs/current/Features/Radicals.html[Open Babel v2.3.1 Radicals and SMILES extensions]

Open Babel supports two SMILES radical extensions: (1) radicals can be interpreted
without defining hydrogens explicitly (e.g., `C[O.]` or `C[O]` for a methoxy radical CH~3~O),
and (2) radical centers can be interpreted with lowercase atomic symbols (e.g., ethyl radical is `Cc`)

There is also support for conjugated carbon chains by interpreting multiple
sequential lower case c without out a ring closure (e.g., `cccc` as conjugated carbon chains.

==== SMARTS

https://openbabel.org/wiki/SMARTS[Open Babel SMARTS]

Open Babel supports Daylight SMARTS with an additional extension to match atom
hybridization with a `^` symbol (e.g., sp^3^ carbon hybridization, `[#6^3]`).

There are several known limitations to the SMARTS support in Open Babel such as
no support for cis/trans stereochemistry and component level grouping.

== RDKit
